version: '3.8'  # Specify a recent Docker Compose file version

services:
  db:
    image: postgres:15.6-alpine3.19  # Use a recent PostgreSQL image
    environment:
      POSTGRES_DB : main_brain
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : sjL8a8QNFzdr!34c
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "python manage.py startup && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: 
