# Generated by Django 4.2.1 on 2023-11-22 10:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        default="header/default.png",
                        upload_to="header/",
                        validators=[core.validators.validate_image_file_extension],
                    ),
                ),
                ("country", models.CharField(default=None, max_length=50, null=True)),
                ("city", models.CharField(default=None, max_length=50, null=True)),
                ("state", models.CharField(default=None, max_length=50, null=True)),
                ("address", models.CharField(default=None, max_length=240, null=True)),
                (
                    "postal_code",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                ("bio", models.TextField(default=None, max_length=5000, null=True)),
                (
                    "occupation",
                    models.CharField(default=None, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "ordering": ["-id"],
            },
        ),
    ]
