# Generated by Django 4.2.1 on 2023-11-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("otp_email", "0004_throttling"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEmailDevice",
            fields=[
                (
                    "emaildevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="otp_email.emaildevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("otp_email.emaildevice",),
        ),
    ]
